name: Build Latest Dictionary Files

on:
  push:
    branches:
      - master
  schedule:
    # 每月3号 执行一遍
    - cron: '0 0 3 * *'

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Prepare Environment
      run: |
          pip3 install -r requirements.txt
          sudo apt install libime-bin

    - name: Build
      run: make zhwiki.dict zhwiki.dict.yaml

    - name: Artifact
      uses: actions/upload-artifact@v3
      with:
        name: zhwiki
        path: zhwiki.dict.yaml

    - name: DeleteWorkflowRuns
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 2
        keep_minimum_runs: 3